export const TOGGLE_PAGE_MODE = 'TOGGLE_PAGE_MODE';

export const NAVIGATE_PAGES_ONCLICK = 'NAVIGATE_PAGES_ONCLICK';
export const NAVIGATE_PAGES_ONSCROLLUP = 'NAVIGATE_PAGES_ONSCROLLUP';
export const NAVIGATE_PAGES_ONSCROLLDOWN = 'NAVIGATE_PAGES_ONSCROLLDOWN';