export const TOGGLE_PAGE_MODE = 'TOGGLE_PAGE_MODE';

export const SET_ACTIVE_PAGE_ONCLICK = 'SET_ACTIVE_PAGE_ONCLICK';
export const SET_ACTIVE_PAGE_ONSCROLLUP = 'SET_ACTIVE_PAGE_ONSCROLLUP';
export const SET_ACTIVE_PAGE_ONSCROLLDOWN = 'SET_ACTIVE_PAGE_ONSCROLLDOWN';