export const TOGGLE_PAGE_MODE = 'TOGGLE_PAGE_MODE';

export const SET_ACTIVE_PAGE_ONCLICK = 'SET_ACTIVE_PAGE_ONCLICK';
export const NAVIGATE_PAGES_ONSCROLLUP = 'NAVIGATE_PAGES_ONSCROLLUP';
export const NAVIGATE_PAGES_ONSCROLLDOWN = 'NAVIGATE_PAGES_ONSCROLLDOWN';